var set = 'basic';
var type = 'scheme';
var lang = 'eng';
var cards = {
	'always' : {
		name: 'A Line in the Sand',
		name: 'Линия на песке',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'doubles' : {
		name: 'Distract',
		name: 'Отвлечение',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'masks' : {
		name: 'Breakthrough',
		name: 'Прорыв',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'crows' : {
		name: 'Assassinate',
		name: 'Покушение',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'tomes' : {
		name: 'Protect Territory',
		name: 'Защита территории',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'rams' : {
		name: 'Bodyguard',
		name: 'Телохранитель',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'1' : {
		name: 'Cursed Object',
		name: 'Проклятая вещь',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'2' : {
		name: 'Outflank',
		name: 'Обход',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'3' : {
		name: 'Plant Evidence',
		name: 'Сфабрикованные улики',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'4' : {
		name: 'Entourage',
		name: 'Прикрытие',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'5' : {
		name: 'Vendetta',
		name: 'Вендетта',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'6' : {
		name: 'Установка зарядов',
		name: '',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'7' : {
		name: 'Make Them Suffer',
		name: 'Заставить их страдать',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'8' : {
		name: 'Deliver a Message',
		name: 'Доставка сообщения',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'9' : {
		name: 'Take Prisoner',
		name: 'Взять пленника',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'10' : {
		name: 'Spring the Trap',
		name: 'Захлопнуть ловушку',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'11' : {
		name: 'Murder Protege',
		name: 'Убийство протеже',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'12' : {
		name: 'Frame For Murder',
		name: 'Основание убийства',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
	'13' : {
		name: 'Power Ritual',
		name: 'Ритуал Силы',
		text:'',
		setup:'',
		special:'',
		vp:'',
	},
}