var set = 'gaining grounds 2018';
var type = 'scheme';
var cards = {
	// 'always' : {
	// 	name:'',
	// 	text:'',
	// 	setup:'',
	// 	special:'',
	// 	vp:'',
	// },
	// 'doubles' : {
	// 	name:'',
	// 	text:'',
	// 	setup:'',
	// 	special:'',
	// 	vp:'',
	// },
	'masks' : {
		name:'Punish the Weak',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'At the end of every Turn after the first, if at least one enemy Minion or Peon model was killed by one of this Crew\'s Henchman or Master models, this Crew earns 1 <b>VP</b>. <p>At the end of every Turn after the first, if the opposing Crew has no Minion or Peon models in play outside of their own Deployment Zone, this Crew earns 1 <b>VP</b>. No more than 1 <b>VP</b> per Turn may be earned from this Scheme.</p>',
	},
	'crows' : {
		name:'Guarded Treasure',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'At the end of every Turn after the first, this Crew earns 1 <b>VP</b> if it has at least two Scheme Markers within 2" of the Centerline, at least 8" apart, and each has at least 1 friendly non-Peon, non-Minion model within 3". After scoring, remove all friendly Scheme Markers within 2" of the Centerline.',
	},
	'tomes' : {
		name:'Eliminate the Leadership',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'The first time the enemy Leader is reduced below half of their starting Wounds, this Crew earns 1 <b>VP</b>.<p>The first time the enemy Leader is reduced to 0 Wounds, Killed, or Sacrificed this Crew earns 1 <b>VP</b>.</p><p>If there is no enemy Leader in play at the end of the game, this Crew earns 1 <b>VP</b>.</p>',
	},
	'rams' : {
		name:'Surround Them',
		text:'',
		setup:'This Scheme may not start revealed.',
		special:'',
		vp:'At the end of the game, this Crew earns 1 <b>VP</b> if it has a Scheme Marker within 6" of a Table Corner in the enemy crew\'s deployment zone.<p> At the end of the game, this Crew earns 1 <b>VP</b> for each other Table Corner with a friendly Scheme Marker within 6" (up to a maximum of 2 <b>VP</b>). Only one Table Corner within this Crew\'s Deployment Zone may count towards this Scheme.</p>',
	},
	'jockers' : {
		name:'Guarded Treasure',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'At the end of every Turn after the first, this Crew earns 1 <b>VP</b> if it has at least two Scheme Markers within 2" of the Centerline, at least 8" apart, and each has at least 1 friendly non-Peon, non-Minion model within 3". After scoring, remove all friendly Scheme Markers within 2" of the Centerline.',
	},
	'1' : {
		name:'Covert Breakthrough',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed.',
		vp:'At the end of the game, this Crew earns 1 <b>VP</b> for each of its Scheme Markers within 6” of the enemy Deployment Zone.',
	},
	'2' : {
		name:'Dig Their Graves',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'Once per turn, after this Crew kills or sacrifices an enemy non-Peon model that is within 4" of one or more Scheme Markers friendly to this Crew, this Crew earns 1 <b>VP</b>. After Scoring, your opponent may remove one Scheme Marker friendly to your Crew within 4" of the killed or sacrificed model.',
	},
	'3' : {
		name:'Set Up',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed.<br>When you choose this Scheme, note down an enemy Master, Henchman, or Enforcer model.<p class="fill"/>',
		vp:'Once per game, at the end of any Turn, this Crew may reveal this Scheme to earn a number of <b>VP</b> equal to the number of this Crew’s Scheme Markers within 4” of the noted enemy model. Then remove all of this Crew’s Scheme Markers within 4” of the noted enemy model.',
	},
	'4' : {
		name:'Hold Up Their Forces',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'At the end of every Turn after the first, this Crew earns 1 <b>VP</b> if at least one of its non-Peon models is engaged with at least two enemy models with no other friendly models engaging them.',
	},
	'5' : {
		name:'Undercover Entourage',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed.<br>When you choose this Scheme, note down one of this Crew’s Master or Henchman models.<p class="fill"/>',
		vp:'At the end of the game, if the chosen model is in the opponent’s half of the table, this Crew earns 1 <b>VP</b>.<p>If the chosen model is in the enemy Deployment Zone at the end of the game, this Crew earns 1 additional <b>VP</b>.</p><p>If the chosen model is in the opponent’s half of the table at the end of the game and has half or more of its Wounds remaining, this Crew earns 1 additional <b>VP</b>.</p>',
	},
	'6' : {
		name:'Inescapable Trap',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'At the end of every Turn after the first, this Crew earns 1 <b>VP</b> if two or more enemy non-Peon models are within 3" of one or more Scheme Markers friendly to this Crew. Then, remove one qualifying Scheme Marker.',
	},
	'7' : {
		name:'Show of Force',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.',
		vp:'At the end of every Turn after the first, count the number of face-up Upgrades with a printed cost greater than 0 attached to each non-Master model within 6” of the center of the board for each Crew. Upgrades which began the game attached to a Master do not count toward this total.<p>If this Crew has at least one qualifying Upgrade and has a number of qualifying Upgrades equal to or exceeding the opposing Crew’s number of qualifying Upgrades, this crew earns 1 <b>VP</b>.</p>',
	},
	'8' : {
		name:'Search the Ruins',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed.',
		vp:'At the end of the game, this Crew earns 2 <b>VP</b> if it has 3 or more Scheme Markers within 6” of the Center of the board and not within 2" of other friendly Scheme Markers. <p>If at least two qualifying Scheme Markers are on the opponent’s half of the table, earn 1 additional <b>VP</b>.</p>',
	},
	'9' : {
		name:'Take Prisoner',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed.<br>When you choose this Scheme, note down an enemy model. <p class="fill"/>',
		vp:'At the end of the game, if this Crew has at least one non-Peon model engaged with the noted enemy model, this Crew earns 2 <b>VP</b>. <p>If this Crew earns any <b>VP</b> from this Scheme and there are no other enemy models within 3” of the noted model, this Crew earns 1 additional <b>VP</b>.</p>',
	},
	'10' : {
		name:'Take One For the Team',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has earned any <b>VP</b> from it.<br>When you choose this Scheme, note one of this Crew’s non-Peon, non-Leader models as the “sucker.”<p class="fill"/>',
		vp:'If the chosen “sucker” model is killed or sacrificed by an enemy model, this Crew earns 1 <b>VP</b>. <p>If the enemy model has a higher Soulstone cost than the "sucker" or was a Master, this Crew earns 1 additional <b>VP</b>. Some Henchman Models have a Soulstone cost of 0, these models count as having a cost of 13 minus their Cache.</p><p>If this Scheme was revealed on or after Turn 4, this Crew earns 1 additional <b>VP</b>.</p>',
	},
	'11' : {
		name:'Recover Evidence',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. You may reveal this Scheme at the beginning of any Turn. After revealing this Scheme, the opponent chooses five of their models in play (or all of their models in play if they have less than five remaining).<p>Place an enemy Evidence Marker in base contact with the models chosen by the opponent.</p>',
		vp:'Models in this Crew may use a (1) Interact Action to remove an enemy Evidence Marker in base contact with itself. If they do, this Crew earns 1 <b>VP</b>.',
	},
	'12' : {
		name:'Vendetta',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed. Reveal this Scheme once this Crew has scored any <b>VP</b> from it.<br>The scheming player notes one of their non-Leader, non-Peon models with a Soulstone cost greater than 0 and an enemy model with a Soulstone cost equal to or greater than the scheming player\'s chosen model.<p class="fill"/><p class="fill"/>',
		vp:'If the noted friendly model\'s first Attack Action in the game is against the noted enemy model, score 1 <b>VP</b> and reveal this Scheme.<br>If the noted enemy model is not in play at the end of the game, and this Scheme has been revealed, score 1 additional <b>VP</b>.<br>If the noted enemy model is killed by the chosen friendly model, score 3 <b>VP</b>.',
	},
	'13' : {
		name:'Public Demonstration',
		text:'',
		setup:'',
		special:'This Scheme may not start revealed.<br>When you choose this Scheme, note down up to three Minion models in this Crew with a combined Soulstone Cost of at least 15.<p class="fill"/><p class="fill"/><p class="fill"/>',
		vp:'Once per game, at the end of any Turn, this Crew may reveal this Scheme to earn 1 <b>VP</b> for each of the noted models within 4” and LoS of an enemy Master, Henchman, or Enforcer.',
	},
}