var set = 'gaining grounds 2016';
var type = 'scheme';
var cards = {
	'always' : {
		name: 'Convict Labor',
		name: 'Каторга',
		text:'Keep that chain gang on task!',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'В конце каждого хода после первого, если этот Отряд has at least three Маркеры Схем within 2" of the Centerline of the board which do not have an enemy модель or another friendly Scheme Marker within 2" of them, этот Отряд scores 1 <b>VP</b>. <p>These Маркеры Схем may still be used to score <b>VP</b> from other Schemes during Turns in which they were not used to score <b>VP</b> for Convict Labor (but they may not be used to Score <b>VP</b> from both Convict Labor and a different Scheme during a single Turn.)</p>',
	},
	'doubles' : {
		name: 'Take Prisoner',
		name: 'Взять пленника',
		text:'Sometimes, you just have to keep someone alive for questioning.',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'При выборе этой схемы, запишите вражескую модель.<p class="fill"/>В конце игры, Если этот Отряд имеет как минимум одну не-Peon модель связанной боем с отмеченной вражеской моделью, этот Отряд получает 2 <b>VP</b>. <p>Если этот Отряд имеет как минимум одну не-Peon модель связанной боем с отмеченной вражеской моделью и нет других вражеских моделей в 3" от отмеченной модели, этот Отряд получает 1 дополнительное <b>VP</b>.</p>',
	},
	'masks' : {
		name: 'Exhaust Their Forces',
		name: 'Истощить их силы',
		text:'Sometimes wearing them out is good enougth.',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'Все не-Peon модели in этот Отряд may target a не-Peon enemy модель within 1" with an Interact Action. If the target has already activated this Turn, it is a (2) Action, else it is a (1) Action. Give the target of the Interact Action the following Condition for the rest of the game: <p><b>Exhausted</b>: This модель gains the following Action: "<b>(1) Shake It Off:</b> Remove the <b>Exhausted</b> Condition from this модель. This Action may not be taken while this модель is engaged." No other Action or Ability can remove this Condition.</p> The first time an enemy модель gains the <b>Exhausted</b> Condition, Откройте эту схему. В конце каждого хода после первого, этот Отряд may end the Exhausted Condition on one enemy модель in play to gain 1 <b>VP</b>.',
	},
	'crows' : {
		name: 'Hunting party',
		name: 'Охотничья вечеринка',
		text:'Hunt them down and make them pay.',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'В конце каждого хода после первого, получите 1 <b>VP</b> если как минимум одна вражеская Minion или Peon модель была убита Enforcer или Henchmen моделью из вашего Отряда . <p>В конце каждого хода после первого, если вражеский Отряд не имеет Minion или Peon моделей в игре, получите 1 <b>VP</b>. Только 1 <b>VP</b> за ход может быть получено от этой схемы.</p>',
	},
	'tomes' : {
		name: 'leave your mark',
		name: 'Оставить метку',
		text:'Let the world know you were here.',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'В конце каждого хода после первого, этот Отряд может убрать один из своих Маркеров Схем находящихся на половине стола противника, не ближе 6" от центральной линии, и не в 4" от вражеской не-Peon модели чтобы получить 1 <b>VP</b>.',
	},
	'rams' : {
		name: 'show of force',
		name: 'Показать силу',
		text:'Sometimes showing up well-armed is all you need to put down a riot.',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'В конце каждого хода после первого, count the number of face-up Upgrades with a printed cost greater than 0 attached to each non-Master модель within 6" of the center of the board for each Crew. Upgrades which began the game attached to a Master do not count toward this total. <p>Если этот Отряд has at least one qualifying Upgrade and has a number of qualifying Upgrades equal to or exceeding the opposing Crew\'s number of qualifying Upgrades, этот Отряд scores 1 <b>VP</b>.</p>',
	},
	'1' : {
		name: 'covert breakthrough',
		name: 'Скрытный прорыв',
		text:'The Crew must push into enemy territory, but keep quiet about it!',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'В конце игры, этот Отряд earns 1 <b>VP</b> за каждый свой Маркер Схем в 6" от вражеской зоны расстановки.',
	},
	'2' : {
		name: 'undercover entourage',
		name: 'Под прикрытием',
		text:'It is vital that an important person be secretly delivered into enemy territory.',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'При выборе этой схемы, запишите одну Master или Henchmen модель из вашего Отряда.<p class="fill"/> В конце игры, если выбранная модель на половине стола противника, этот Отряд получает 1 <b>VP</b>. <p>Если выбранная модель во вражеской зоне расстановки в конце игры, этот Отряд получает 1 дополнительное <b>VP</b>.</p><p>if the chosen модель is in the opponent\'s half of the table в конце игры and has half or more of its Wounds remaining, этот Отряд получает 1 дополнительное <b>VP</b>.</p>',
	},
	'3' : {
		name: 'neutralize the leader',
		name: 'Нейтрализация лидера',
		text:'Cut off the head, and the snake will die.',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'The first time the enemy Leader is reduced below half of their starting Wounds, gain 1 <b>VP</b>. <p>The first time the enemy Leader leaves play, score 2 <b>VP</b>.</p>',
	},
	'4' : {
		name: 'catch and release',
		name: 'Поймать и отпустить',
		text:'The flora and fauna of Malifaux must be catalogued!',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'Все не-Peon модели in этот Отряд may target a не-Peon enemy модель within 1" with a (1) Interact Action to give the target the following Condition for the rest of the game: <p><b>Tagged</b>: this модель gains the following Action:"<b>(2) Rip It Out:</b> Remove this Condition from this модель. This Action may not be taken while this модель is engaged." No other Action or Ability can remove this Condition.</p> <p>The first time an enemy модель gains the <b>Tagged</b> Condition, Откройте эту схему. At the end of every Turn, этот Отряд earns 1 <b>VP</b> if at least two enemy модели in play have <b>Tagged</b> Condition.</p>',
	},
	'5' : {
		name: 'frame for murder',
		name: 'Основание убийства',
		text:'Convince the enemy leader to kill some poor sap!',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'При выборе этой схемы, note one of этот Отряд\'s не-Peon модель as the "sucker". If the chosen "sucker" модель is killed or sacrificed by an enemy модель, score 1 <b>VP</b>. <p>If the enemy модель was a Master or Henchmen, score 1 additional <b>VP</b>.</p> If this Scheme was accomplished on before Turn 3, score 1 additional <b>VP</b>.',
	},
	'6' : {
		name: 'detonate the charges',
		name: 'Взорвать заряды',
		text:'It\'s time to blow some stuff up!',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'Раз за игру, в конце любого хода, этот Отряд может открыть эту схему и получить 1 <b>VP</b> за каждую вражескую модель that is within 3" of at least one of этот Отряд\'s Маркеры Схем. Then, remove all of этот Отряд\'s Маркеры Схем which are within 3" of an enemy модель. <p>If only one Scheme Marker is removed in this way, этот Отряд can only score a maximum of 2 <b>VP</b> from this Scheme.</p>',
	},
	'7' : {
		name: 'set up',
		name: 'Расстановка',
		text:'Get the enemy right where you want them and then spring your trap!',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'При выборе этой схемы, запишите an enemy Master, Henchmen, or Enforcer модель.<p class="fill"/> <p>Раз за игру, в конце любого хода, этот Отряд may Откройте эту схему to score a number of <b>VP</b> equal to the number of этот Отряд\'s Маркеры Схем within 4" of the noted модель. Then remove all of этот Отряд\'s Маркеры Схем within 4" of the noted модель.</p>',
	},
	'8' : {
		name: 'search the ruins',
		name: 'Обыск руин',
		text:'The ruins dotting Malifaux\'s surface are ancient and terrible; there is no telling what you may learn from their excavation.',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'В конце игры, этот Отряд earns 2 <b>VP</b> if it has 3 or more Маркеры Схем within  6" of the Center of the board. <p>If at least two of those Маркеры Схем are on the opponent\'s half of the table, earn 1 additional <b>VP</b>.</p> Маркеры Схем which are within 2" of one or more other friendly Маркеры Схем do not count towards this Scheme.',
	},
	'9' : {
		name: 'mark for death',
		name: 'Отмеченный смертью',
		text:'It\'s always good to keep the slaughter organized.',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'Все не-Peon модели in этот Отряд may target a не-Peon enemy модель they are engaged with with a (1) Interact Action to give the target the following Condition for the rest of the game: <p>"<b>Marked</b>: This condition may not be removed or ended."</p> Откройте эту схему как только an enemy модель gains the <b>Marked</b> condition. When an enemy модель with the <b>Marked</b> Condition is reduced to 0 Wounds or leaves play, gain 1 <b>VP</b>.',
	},
	'10' : {
		name: 'public demonstration',
		name: 'Публичный показ',
		text:'Make your voice heard!',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'При выборе этой схемы, тайно запишите до трех Minion моделей в этом Отряде с общей Soulstone Cost не меньше 15.<p class="fill"/><p class="fill"/><p class="fill"/> <p>Раз за игру, в конце любого хода, этот Отряд may Откройте эту схему to score 1 <b>VP</b> for each of the noted модели within 4" and LoS of an enemy Master, Henchman, or Enforcer.</p>',
	},
	'11' : {
		name: 'inspection',
		name: 'Инспекция',
		text:'Time to bust some doors and flip some beds!',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'В конце каждого хода после первого, этот Отряд scores 1 <b>VP</b> if it has at least one не-Peon модель within 4" of where each end of the Centerline of the board meets the board edge (or corner).',
	},
	'12' : {
		name: 'a quick murder',
		name: 'Быстрое убийство',
		text:'There is nothing like a quick murder to get things started!',
		setup:'Эта схема не может начаться открытой. Откройте эту схему как только этот Отряд получил <b>VP</b> за нее.',
		special:'',
		vp:'При выборе этой схемы, запишите the enemy модель with the highest Soulstone Cost.<p class="fill"/> If the multiple модели are tied for the highest Soulstone Cost, then choose one of those модели and note it down. <p>этот Отряд earns 2 <b>VP</b> if the noted модель is killed or sacrificed before the end of the game.</p> If the noted enemy модель is killed or sacrificed on or before Turn 3, earn 1 additional <b>VP</b>.',
	},
	'13' : {
		name: 'occupy their turf',
		name: 'Занять их земли',
		text:'Take everything they have.',
		setup:'Эта схема не может начаться открытой.',
		special:'',
		vp:'Раз за игру, в конце любого хода, этот Отряд may Откройте эту схему to score a number of <b>VP</b> equal to the number of этот Отряд\'s Minion модели on the enemy half of the board which are not within 10" of the Centerline.',
	},
}