var talents = {
	general :{
		book:'Fated Almanac',
		'Armor Training' : {
				name:'Тренированная Броня',
				requirement:'Нет',
				story:'Умный человек не просто носит броню, но изучает как правильно ее использовать.',
				text:'Вы снижаете штраф к защите (Defense) от ношения брони на 1, до минимума в 0.',
				trigger:'',
				limit:'Вы можете брать этот талант несколько раз.',
			},
		'Better Part of Valor' : {
				name:'Лучшая часть доблести',
				requirement:'Стойкость (Tenacity) -1 или ниже.',
				story:'Когда ситуация становиться жесткой, пожалуй лучше пойти в другую сторону!',
				text:'Ваше нападение (Charge) становиться “—” но вы получаете +2 к Движению (Walk).',
				trigger:'',
				limit:'',
			},
		'Blissful Ignorance' : {
				name:'Блаженное неведенье',
				requirement:'Хитрость (Cunning) -1 или ниже.',
				story:'Зачастую вы не замечаете деталей вокруг себя и это может оказаться полезным!',
				text:'При провале дуэли страха (Horror Duel), вы получаете состояние замедлен (Slow), а не парализован (Paralyzed).',
				trigger:'',
				limit:'',
			},
		'Call Shot' : {
				name:'Заявленный выстрел',
				requirement:'Нет',
				story:'Пули летят туда, куда хотите вы.',
				text:'Выберите навык. Когда вы создаете Критический Эффект (Critical Effect) атакой, использующей выбранный навык, вы можете сбросить карту чтобы поменять масть Критического Эффекта на масть сброшенной карты.',
				trigger:'',
				limit:'Вы можете взять этот Талант несколько раз, каждый раз вы должны выбирать разный навык.',
			},
		'Calm & Collected' : {
				name:'Спокойный и собранный',
				requirement:'Скорость (Speed) -1 или ниже.',
				story:'Вы познали, что спешка ведет только к ошибкам.',
				text:'ВЫ добавляете +1 к значению состояния Сфокусирован (Focused) на себе (например считая "Сфокусирован + 1" как "Сфокусирован + 2"). Оно все еще не может превысить "Сфокусирован + 3".',
				trigger:'',
				limit:'',
			},
		'Clear Orders' : {
				name:'Четкие приказы',
				requirement:'Лидерство (Leadership) 3 или выше.',
				story:'Вы раздаете четкие и краткие приказы.',
				text:'Когда вы выполняете действие Приказ (Order Action), вы можете обмануть судьбу (Cheat Fate) за получающего приказ персонажа.',
				trigger:'',
				limit:'',
			},
		'Combat reading' : {
				name:'Чтение битвы',
				requirement:'Хитрость (Cunning) 1 или выше.',
				story:'Вы способны считывать цель во время битвы и атаковать в открывающиеся бреши, которых другие не заметят.',
				text:'При совершении удерживающего удара (disengaging strike), вы добавляете половину своего навыка Контроля (Scrutiny) в дополнение к действующему значению (Acting value).',
				trigger:'',
				limit:'',
			},
		'Counter-spell' : {
				name:'Противодействие заклинаниям',
				requirement:'Противодействие заклинаниям (Counter-spell) 3 или выше.',
				story:'Тренировка в искусстве противодействия заклинаниям дала вам способность интуитивно сопротивляться магии.',
				text:'Когда вы являетесь целью магической атаки или действия, атакующий теряет любые масти ассоциированные с его магическим навыком (Magical)',
				trigger:'',
				limit:'',
			},
		'Critical strike' : {
				name:'Критический удар',
				requirement:'Специализированный (Specialized) с выбранным навыком.',
				story:'Опытный атакующий зачастую может нанести больше урона чем дилетант (или обычный бандит) и вы не являетесь исключением.',
				text:'Выберите навык. Все атаки с выбранным навыком получают следующий триггер:',
				trigger:'♥ "Критический удар": При нанесении урона добавьте 1 дополнительную единицу урона за каждую ♥ в итоговом значении.',
				limit:'Вы можете взять этот Талант несколько раз, каждый раз вы должны выбирать разный навык.',
			},
		'Cynic' : {
				name:'Циник',
				requirement:'Обаяние (Charm) -1 или ниже.',
				story:'Если похоже, что вам лгут, то вполне вероятно вы назовете кого-то лжецом.',
				text:'Вы получаете "+" на любые дуэли по сопротивлению обману (deception)',
				trigger:'',
				limit:'',
			},
		'Flick of the Wrist' : {
				name:'Легким движением руки',
				requirement:'Сила (Might) -1 или ниже.',
				story:'Вы познали как использовать точность с оружием там где другие полагаются на грубую силу.',
				text:'Совершая атаку ближнего боя (Close Combat) с оружием удерживаемым в одной руке, вы можете использовать Грацию (Grace) вместо Силы (Might) при вычислении Действующего Значения (Acting value).',
				trigger:'',
				limit:'',
			},
		'Governor’s Gift' : {
				name:'Подарок Губернатора',
				requirement:'Обаяние (Charm) 1 или выше.',
				story:'Некоторые люди на короткой ноге с представителями определенного пола.',
				text:'Выберите мужчину или женщину. Вы получаете "+" на любую дуэль Очарования (Bewitch) или Контроля (Scrutiny) против представителей выбранного пола.',
				trigger:'',
				limit:'',
			},
		'Great Fate' : {
				name:'Великая судьба',
				requirement:'Нет',
				story:'Судьба улыбается вам, позволяя управлять собой чаще.',
				text:'Вы тянете дополнительную карту в начале каждой игровой сессии.',
				trigger:'',
				limit:'Вы можете брать этот талант несколько раз и эффект накапливается. Но после вытягивания карт в начале игры, необходимо сбросить карты до 5, если их больше на руке.',
			},
		'Gruff' : {
				name:'Грубоватый',
				requirement:'Обаяние (Charm) -1 или ниже.',
				story:'Когда вы говорите, присутствует некий перегиб и столь явный, что его очень тяжело понять.',
				text:'Дуэли Контроля (Scrutiny) против вас получают "-".',
				trigger:'',
				limit:'',
			},
		'Hard to Kill' : {
				name:'Трудно убить',
				requirement:'Выносливость (Resilence) +1 или выше.',
				story:'Вы можете получить сильные повреждения, но продолжать идти вперед.',
				text:'Вы можете проигнорировать один Критический Эффект per Dramatic Time.',
				trigger:'',
				limit:'',
			},
		'Hobbling attack' : {
				name:'Хромающая атака',
				requirement:'Специализированный (Specialized) с выбранным навыком.',
				story:'Вы можете всадить пулю так, чтобы помимо нанесения урона замедлить цель',
				text:'Выберите навык. Все атаки с выбранным навыком получают следующий триггер:',
				trigger:'♠ "Хромота": После успеха, цель получает следующее состояние до конца Dramatic Time: "Хромой: Этот персонаж может заявлять только одно действие движения (Movement General Action) в ход."',
				limit:'',
			},
		'Honest' : {
				name:'Честный',
				requirement:'Хитрость (Cunning) -1 или ниже.',
				story:'Вам нет необходимости убеждать окружающих доверять вам, все видят вашу честную природу.',
				text:'Вы получаете "+" на все дуэли Убеждения (Convince) и Лидерства (Leadership) против нейтральных и дружественных персонажей (тех кто либо заинтересован в вашем успехе, либо безучастны к вашему существованию как констебль или бюрократ).',
				trigger:'',
				limit:'',
			},
		'Imposing Mass' : {
				name:'Внушительная масса',
				requirement:'Грация (Grace) -1 или ниже.',
				story:'Вы не можете передвигаться ловко и научились использовать свои неточные движения в своих интересах.',
				text:'Вы получаете "+" на дуэли удерживающего удара (disengaging strike)',
				trigger:'',
				limit:'',
			},
		'Ingenious' : {
				name:'Находчивый',
				requirement:'Сила (Might) -1 или ниже.',
				story:'Чтобы противостоять частой неспособности открыть упрямые банки с вареньем, вы стали умело использовать инструменты.',
				text:'Вы добавляете половину своего Интеллекта (Intellect) к любым дуэлям, которые обычно требуют инструменты (такие как Ремесло (Crafting)).',
				trigger:'',
				limit:'',
			},
		'Just a Graze' : {
				name:'Просто царапина',
				requirement:'Обреченный',
				story:'Удача благоволит дуракам, а вы имеете странное свойство принимать удары нужным местом.',
				text:'Вы можете подтасовывать урон (Cheat Damage Flips) который получаете, покуда Переворот Урона не имеет "+".',
				trigger:'',
				limit:'',
			},
		'Open Hand Fighting' : {
				name:'Рукопашный бой',
				requirement:'Нет',
				story:'Свободная рука (или две) имеет свои преимущества.',
				text:'Если вы орудуете одним одноручным оружием, вы можете наносить урон при проведении удерживающих ударов (disengaging strikes).',
				trigger:'',
				limit:'',
			},
		'Paired Weapons' : {
				name:'Парное оружие',
				requirement:'Выбранный навык ранга 3 или выше',
				story:'Два оружия лучше чем одно... Правда? Вы способны эффективно орудовать двумя одноручными оружиями.',
				text:'Выберите навык Ближнего (Close Combat) или Дальнего боя (Ranged) с рангом 3 или выше. Вы получаете "+" к Перевороту Атаки когда владеете двумя оружиями. Стоит отметить, что это несовместимо с оружием требующим двух рук. Вы совершаете только один Переворот Атаки для обоих оружий.',
				trigger:'',
				limit:'',
			},
		'Plain Spoken' : {
				name:'Обычный разговорный',
				requirement:'Интеллект (Intellect) -1 или ниже.',
				story:'Вы не пытаетесь засорять свой разговор цветастыми выражениями и хороши в произнесении тяжелой правды простым языком.',
				text:'Вы получаете "+" к Социальным (Social) дуэлям во время Dramatic Time.',
				trigger:'',
				limit:'',
			},
		'Quick Study' : {
				name:'Быстрое обучение',
				requirement:'Интеллект (Intellect) +1 или выше.',
				story:'Некоторые люди быстро учаться просто наблюдая за окружающими.',
				text:'Когда вы должны получить навык, вы можете выбрать навык, которого у вас нет и в использовании которого дружественный персонаж преуспел во время игровой сессии, вместо вариантов предоставленных Мастером.',
				trigger:'',
				limit:'',
			},
		'Rush' : {
				name:'Спешка',
				requirement:'Скорость (Speed) 1 или выше.',
				story:'Вы хороши в ввязывании в битву, связывая противника жестоким ближним боем.',
				text:'ВЫ получаете +1 к своему аспекту Нападения (Charge).',
				trigger:'',
				limit:'Вы можете брать этот талант несколько раз и эффект накапливается.',
			},
		'Scoundrel' : {
				name:'Подлец',
				requirement:'Есть те, кто буквально очаровывает деньги из чужого кошелька.',
				story:'Вы получаете следующий триггер на все Социальные испытания (Social Challenges):',
				text:'♦: "Выполнить карманную кражу" (Pick Pocket Action)(не требует ОД) как часть разрешения Социального действия (Social Action). Карманная кража получает "+".',
				trigger:'',
				limit:'',
			},
		'Shot Studies' : {
				name:'Исследование выстрелов',
				requirement:'Дробовик (Shotgun) 3 или выше.',
				story:'Дальность карабина или дробовика - ваша вторая натура.',
				text:'Вы увеличиваете дальность (range) карабина (Carbine) или дробовика (Shotgun) стреляющего пулями (slugs) на 10 если у вас есть состояние "Сфокусирован + 1" (или выше). В отличие от способности ружья, дальность увеличивается только на 10 в независимости от значения сфокусированности.',
				trigger:'',
				limit:'',
			},
		'Shove Aside' : {
				name:'Толчок в сторону',
				requirement:'Сила (Might) 1 или выше.',
				story:'Вы можете проходить мимо других с незначительным сопротивлением.',
				text:'Вы можете безпрепятственно проходить сквозь персонажей с высотой (Height) ниже чем у вас. Эти персонажи все еще могут делать удерживающие удары (disengaging strikes) против вас.',
				trigger:'',
				limit:'',
			},
		'Shrug Off' : {
				name:'Отмахнуться',
				requirement:'Выносливость -1 или меньше либо происхождение "Ортега"',
				story:'Вы настолько привыкли к незначительной боли, болезням, или другим препятствиям, что можете их игнорировать как типичный фон своего существования.',
				text:'Вы получаете следующее тактическое действие:',
				trigger:'(0) "Отмахнуться": Вы можете сбросить карту чтобы убрать одно состояние (condition) с себя.',
				limit:'',
			},
		'Simple Logic' : {
				name:'Простая Логика',
				requirement:'Интеллект (Intellect) -1 или ниже.',
				story:'Вы не усложняете и склоняетесь к черно белому представлению о вещах.',
				text:'Вы получаете "+" к сопротивлению дуэлям Очарования (Bewitch), Убеждения (Convince) и Обмана (Deceive) направленным против вас.',
				trigger:'',
				limit:'',
			},
		'Skill Mastery' : {
				name:'Мастер навыка',
				requirement:'???',
				story:'Есть те к кому приходит мастерство по мере тренировок.',
				text:'Выберите навык. Вы получаете "+" на все Перевороты Испытания (Challenge Flips) с данным навыком.',
				trigger:'',
				limit:'Вы можете взять этот Талант несколько раз, каждый раз вы должны выбирать разный навык.',
			},
		'Specialized skill' : {
				name:'Специализированный навык',
				requirement:'Обреченный',
				story:'Вы оттачивали определенное умение, позволяющее выполнять трюки с небольшим усилием.',
				text:'Выберите навык и масть. Добавьте масть к знчению выбранного навыка.',
				trigger:'',
				limit:'Вы можете взять этот Талант несколько раз, каждый раз вы должны выбирать разный навык.',
			},
		'Sturdy' : {
				name:'Крепкий',
				requirement:'Грация (Grace) -1 или ниже.',
				story:'Вы признаете, что плохой танцор и не можете нормально стоять на одной ноге... но вы выносливее многих, а это чего-то да стоит.',
				text:'Вы получаете +1 Рану (Wounds).',
				trigger:'',
				limit:'',
			},
		'Sure-Footed' : {
				name:'Неспотыкающийся',
				requirement:'Скорость (Speed) -1 или ниже.',
				story:'Вы не можете двигаться быстро, но вас также трудно сдвинуть с места.',
				text:'Вы можете применять свою скорость как штраф к дистанции на которую вы сдвигаетесь (push) эффектом.',
				trigger:'',
				limit:'',
			},
		'Twisted Fates' : {
				name:'Искаженные судьбы',
				requirement:'Обреченный',
				story:'Удача благоволит подготовленным, как говорится, но вы кажется, можете направлять удачу чаще чем большинство.',
				text:'Выберите карту в своей колоде и увеличьте или уменьшите ее значение на 1. Смена значения не должна привести к двум одинаковым картам (масть + число). Например вы можете иметь две 8 но с разными мастями.',
				trigger:'',
				limit:'Вы можете взять этот Талант несколько раз.',
			},
		'Unassuming' : {
				name:'Скромный',
				requirement:'Сила (Might) -1 или меньше.',
				story:'Всю жизнь имея дело с теми, кто сильнее выс, вы научились относиться к происходящему спокойно и гармонично.',
				text:'Вы получаете "+" к любой дуэли на избежание быть замеченным или разозлить кого-то.',
				trigger:'',
				limit:'',
			},
		'Undermine Confidence' : {
				name:'Подорвать Доверие',
				requirement:'Выносливость (Resilence) -1 или ниже.',
				story:'Иногда лучше много говорить и позволить нервозности спасть.',
				text:'Вы получаете "+" на все дуэли Запугивания (Intimidation) выполняемые вне Dramatic Time.',
				trigger:'',
				limit:'',
			},
		'Unequaled Accuracy' : {
				name:'Непревзойденная Точность',
				requirement:'рейтинг выбранного навыка 2 или выше.',
				story:'Мало тех, у кого непревзойденное чувство времени при всаживании снаряда.',
				text:'Вы не определяете цель случайно при стрельбе в связанную боем цель.',
				trigger:'',
				limit:'',
			},
		'Unimpeded' : {
				name:'Беспрепятственный',
				requirement:'Грация (Grace) 1 или выше.',
				story:'Вы ловко ставите ноги при перемещении, там где другие сталкиваются с трудностями.',
				text:'Вы игнорируете штрафы от местности (такие как мокрая земля или щебень) при выполнении действия Движения.',
				trigger:'',
				limit:'',
			},
		'Wall of Muscle' : {
				name:'Стена Мускулов',
				requirement:'Выносливость (Resilence) 1 или выше.',
				story:'Вы высоки и широки и знаете как использовать это в свою пользу.',
				text:'Повысьте вашу высоту (Height) до 3. Также увеличьте дальность всего оружия ближнего боя, которым владеете на 1, до максимума в 3.',
				trigger:'',
				limit:'',
			},
		'Will of Ages' : {
				name:'Воля веков',
				requirement:'Стойкость (Tenacity) 1 или выше.',
				story:'',
				text:'Вы можете защитить больше одного дружественного персонажа своим навыком Противодействие заклинаниям (Counter-spelling).При использовании Магического щита (стр 245) вы можете защитить дружественных персонажей (включая себя) в количестве равном вашей Стойкости (Tenacity)',
				trigger:'',
				limit:'',
			},
	},
	academic : {
		book:'Fated Almanac',
		'Avid Student' : {
				name:'Заядлый студент',
				requirement:'',
				story:'',
				text:'При провале Academic duel, можно вытянуть карту на руку. Эпилог: можно развить любой Academic skill в дополнение к вариантам развития навыков.',
				trigger:'',
			},
		'Student of Knowledge' : {
				name:'Студент познания',
				requirement:'',
				story:'У вас случаются частые вспышки гениальной проницательности.',
				text:'Он получает следующий триггер на все дуэли Академических навыков:',
				trigger:'♣ Озарение: После решения, возьмите карту на руку.',
			},
		'Eureka Moment' : {
				name:'Эврика',
				requirement:'',
				story:'An epiphany is a powerful thing, especially among those with the intellectual prowess to realize how important a new discovery is.',
				text:'The character gains the following Trigger on all Academic skills:',
				trigger:'♣: Gain 2 additional Margins of Success.',
			},
		'Great Thinker' : {
				name:'Великий мыслитель',
				requirement:'',
				story:'As one of the greatest minds in Academia, the character is paralleled by few within his field.',
				text:'Choose a single Academic skill, the maximum rating for this skill is 6 (instead of 5).',
				trigger:'A character may have the Great Thinker Talent multiple times, but each time a different skill must be chosen.',
				limit:'',
				fill:3,
			},
		'Rational Mind' : {
				name:'Рациональный ум',
				requirement:'',
				story:'A calm and clear head allows the character to avoid manipulation through illusion or deceit.',
				text:'Whenever the character must make a Challenge Flip to resist an act of manipulation (such as terror, mind control, or intimidation) the character may use his choice of Cunning or Intellect instead of the normal Aspect.',
				trigger:'',
				limit:'',
			},
		'Applied Learning' : {
				name:'Прикладное обучение',
				requirement:'',
				story:'Knowledge must be applied to have use, and the character has learned some tricks for using a skill in new ways. ',
				text:'Choose an Academic skill as well as a secondary skill. Whenever the character makes a skill Challenge with the secondary skill, he may exchange the chosen Academic skill rating for the Aspect rating used. Note: The combination of skills selected must be approved by the Fatemaster, as some Fatemasters may not feel that certain combinations (such as Literacy and Dodge) make logical sense in their campaign.',
				trigger:'',
				limit:'A character may have the Applied Learning Talent multiple times, but each time a new combination of Academic skill and secondary skill must be chosen.',
				fill:2,
			},
		'Sum of All Knowledge' : {
				name:'Сумма всех знаний',
				requirement:'',
				story:'Capable of great leaps of logic, the character is able to translate knowledge in one field into many others.',
				text:'Whenever the character must make a Cunning or Intellect based Challenge Flip, he may add an additional bonus equal to half of any one Academic skill rating (rounding down) to his Initial Acting value. The Academics skill used must have the same Associated Aspect as the Challenge Flip to be modified.',
				trigger:'',
				limit:'',
			},
	},
	criminal : {
		book:'Fated Almanac',
		'Opportunist' : {
				name:'Оппортунист',
				requirement:'',
				story:'',
				text:'При провале Expertise duel, можно вытянуть карту на руку. Эпилог: можно развить любой Expertise skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Competitive Edge' : {
				name:'Конкурентное преимущество',
				requirement:'',
				story:'The character is able to make good guesses, relying on his instincts.',
				text:'This character gains the following Trigger on all Expertise skill Duels:',
				trigger:'♦ Fortunate: After resolving, draw a Twist card.',
				limit:'',
			},
		'Improvise' : {
				name:'Импровизация',
				requirement:'',
				story:'Some men grow adept at making do without tools, even if it takes them a bit longer.',
				text:'Choose a skill. This character is always considered to have a tool kit of the chosen skill.',
				trigger:'A Character may have this ability multiple times, but each time a different skill must be chosen.',
				limit:'',
				fill:2,
			},
		'Quick Work' : {
				name:'Бастрая работа',
				requirement:'',
				story:'The character is able to perform a skill far more rapidly than normally.',
				text:'Reduce the AP cost by 1 of the first Use skill Action made by the Character during each Turn (to a minimum of 0).',
				trigger:'',
				limit:'',
			},
		'Nimble' : {
				name:'Юркий',
				requirement:'',
				story:'This character is ready to move at a moment’s notice, and is able to do so without much focus.',
				text:'This character generates an additional AP on his turn, but the AP must be used to take a Movement General Action.',
				trigger:'',
				limit:'',
			},
		'Surprise Assault' : {
				name:'Внезапный удар',
				requirement:'',
				story:'The character is adept at making attacks against an unprepared opponent, either from hiding or just making the first move.',
				text:'Any of the character’s attacks gain + to the Challenge Flip and Damage Flip when he attacks before any other character acts during Dramatic Time.',
				trigger:'A character may have this Talent more than once, gaining a + each time.',
				limit:'',
				fill:2,
			},
		'Master of Misdirection' : {
				name:'Мастер дезориентации',
				requirement:'',
				story:'Some characters are better at working with a group than most.',
				text:'When this character succeeds on a (1) Trick Challenge, anyone attacking the target gains +, instead of just the acting character. As well, this character gains + to defend against attacks that anyone makes while they are suffering from the effects of the Trick, even someone else’s Trick.',
				trigger:'',
				limit:'',
			},
	},
	dabbler : {
		book:'Fated Almanac',
		'Epiphany' : {
			name:'Богоявление',
			requirement:'',
			story:'',
			text:'После провала Магической дуэли во время dramatic time, можно вытянуть карту на руку. Эпилог: можно развить любой Магический (Magical) навык в дополнение к вариантам развития навыков.',
			trigger:'',
			limit:'',
			},
		'Arcane Musings' : {
			name:'Таинственные размышления',
			requirement:'',
			story:'Часть вашего сознания постоянно замечает таинственные стороны мира, готовя разум к работе с чудесами.',
			text:'Вы убираете одну ♣ из сложности (TN) любого заклинания, которое он колдует.',
			trigger:'',
			limit:'',
			},
		'Empowered Channeling' : {
			name:'Усиленная проводимость',
			requirement:'',
			story:'Когда вы решаете направить заклинание более аккуратно оно наполняется еще большей силой.',
			text:'При исполнении заклинания, вы повышаете номер соего состояния "Сфокусирован" на 1. Этот талант действует только если у вас есть состояние "Сфокусирован" (вы не получет его если не имеете).',
			trigger:'',
			limit:'',
			},
		'Mastered Magia' : {
			name:'Освоенная Магия',
			requirement:'',
			story:'Чтобы считаться мастером Магии, нужно потратить существенное время на тайные искусства.',
			text:'Выберите Магию (Magia) которая доступна вам минимум в одном Гримуаре (Grimoire). Когда вы колдуете заклинание из любого Гримуара, вы можете использовать выбранную Магию. Также, Если вы не имеете Гримуара, вы можете действовать как если бы владели Гримуаром с выбранной Магией в нем. Это значит, что вы может колдовть заклинание без Гримуара если вы освоили соответствующие Магию и Иммуто.',
			trigger:'',
			limit:'',
			fill:3,
		},
		'Mastered Immuto' : {
			name:'Освоенный Иммуто',
			requirement:'',
			story:'Долгие часы практики привели к освоению одного магического Иммуто.',
			text:'Выберите Иммуто (Immuto) который доступен вам минимум в одном Гримуаре (Grimoire). Когда вы колдуете заклинание из любого Гримуара, вы можете использовать выбранный Иммуто.',
			trigger:'',
			limit:'',
			fill:2,
		},
		'Spell Affinity' : {
			name:'Родство с заклинанием',
			requirement:'',
			story:'Периодическое использование сроднило вас с одним из компонентов определенного заклинания.',
			text:'Выберите определенный Иммуто (Immuto) или Магию (Magia). Все проверки на колдовство или защиту от заклинания содержащего выбранный Genus, Immuto, or Magia получают "+".',
			trigger:'',
			limit:'Вы можете взять этот Талант несколько раз, но каждый раз разный Genus, Immuto, or Magia должен быть выбран. Также, вы можете получить преимущество только от одного Родства с заклинанием в рамках проверки.',
			fill:3,
		},
	},
	drudge : {
		book:'Fated Almanac',
		'Hard days night' : {
				name:'Ночь после тяжелого дня',
				requirement:'',
				story:'',
				text:'При провале дуэли Тренировки (Training), можно вытянуть карту на руку. Эпилог: можно развить любой навык Тренировки (Training) в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Long Days' : {
				name:'Долгие дни',
				requirement:'',
				story:'Некоторые дни просто не кончаются и вы способны преодолеть себя там, где другие сломаются.',
				text:'Вы можете сбросить карту чтобы автоматически пройти любую дуэль Бессознательности (Unconsiosness Challenge). Также вы получает следующий триггер на все дуэли Выносливости (Resilence) и Стойкости (Tenacity) (исключая дуэли Защиты (Defence) или Силы Воли (Willpower Duels)):',
				trigger:'♥ Выздороветь: После определения результата, вылечить 1 рану.',
				limit:'',
			},
		'Steady Pace' : {
				name:'Размеренный темп',
				requirement:'',
				story:'Усилия прилагаемые на стабильной скорости, для вас, намного более эффективны чем внезапные всплески энергии.',
				text:'Во время an Продолжительного испытания (Ongoing Challenge), если вы успешны при проверке вы получает "+" к следующей проверке.',
				trigger:'',
				limit:'Вы можете взять этот талант до трех раз и эффекты складываются.',
				fill:3,
			},
		'Team Work' : {
				name:'Командная работа',
				requirement:'',
				story:'',
				text:'Помогая другому или получая помощь, вы добавляете дополнительный "+" к проверке.',
				trigger:'',
				limit:'Вы можете взять этот талант до двух раз и эффекты складываются.',
				fill:2,
			},
		'Slow To Die' : {
				name:'Медлящий умирать',
				requirement:'',
				story:'Требуется больше усилий чтобы действительно ранить вас.',
				text:'Проверки критических эффектов (Critical Effect Flips) против вас получают "-".',
				trigger:'',
				limit:'Вы можете взять этот талант до трех раз и эффекты складываются.',
				fill:3,
			},
		'Long Suffering' : {
				name:'Долгие страдания',
				requirement:'',
				story:'Годы не были добры, но вы научились не ожидать подобной доброты.',
				text:'Вы можете использовать Выносливость (Resilence) вместо Стойкости (Tenacity), или наоборот, при подсчете Действующего Значения для проверки использующей один из этих аспектов.',
				trigger:'',
				limit:'',
			},
		'Cant\'t Keep Me Down' : {
				name:'Меня не сломить',
				requirement:'',
				story:'Требуется многое чтобы вывести вас из боя.',
				text:'Вы можете сбросить карту с руки, чтобы игнорировать негативные эффекты всех Критических Эффектов до конца своего хода. Это не излечивает эффекты, вы просто пробиваетесь сквозь боль, или выводите свое тело за рамки ограничений.',
				trigger:'',
				limit:'',
			},
	},
	graverobber : {
		book:'Fated Almanac',
		'Black soul' : {
				name:'Черная душа',
				requirement:'',
				story:'',
				text:'После провала дуэли Magic duel во время dramatic time, можно вытянуть карту на руку. Эпилог: можно развить любой Magical skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Morbid Thoughts' : {
				name:'Нездоровые мысли',
				requirement:'',
				story:'This is a character who is constantly dwelling on death and its power, making some magic much easier to cast.',
				text:'This character removes a single ♠ from the TN of any Spell he casts.',
				trigger:'',
				limit:'',
			},
		'Deathly Pallor' : {
				name:'Мертвенная бледность',
				requirement:'',
				story:'Time spent among the dead (or undead) has given this character an unmistakable aura of the grave.',
				text:'The character gains + to any challenge to Intimidate or strike fear (including Spells).',
				trigger:'',
				limit:'',
			},
		'Macabre Infusions' : {
				name:'Жуткие настойки',
				requirement:'',
				story:'Time spent around necromantic energies and locations has infused the character’s body with death like qualities.',
				text:'The character counts as undead as well as Living if he wishes.',
				trigger:'This also means that many undead will treat the character with disinterest (instead of attacking him), per the Fatemaster’s discretion.',
				limit:'',
			},
		'Unholy Beacon' : {
				name:'Нечистый маяк',
				requirement:'',
				story:'The undead bow to the character’s whims.',
				text:'The character may discard a card from his Control Hand to take control of any undead (including natural undead, or undead under another character’s control). The undead acts as if it were the character’s minion.',
				trigger:'Sentient undead may resist this ability. The character must succeed on a Charm + Necromancy Challenge Flip against the sentient undead’s Tenacity + Resilience to dominate it.',
				limit:'',
			},
		'Mastered Magia' : {
			requirement:'Освоенная Magia',
			name:'',
			story:'To be considered a master of a Magia, one must devote considerable time to the arcane arts.',
			text:'Choose a Magia which the character has access to in at least one Grimoire. Whenever the character casts a Spell from any Grimoire, he may use the chosen Magia. In addition, if the character does not have a Grimoire, he may act as if he possessed a Grimoire with the chosen Magia in it. This means that he may cast a Spell without a Grimoire if he has mastered the appropriate Magia and Immuto.',
			trigger:'',
			limit:'',
			fill:3,
		},
		'Masterd Immuto' : {
			name:'Освоенный Immuto',
			requirement:'',
			story:'Long hours of use has led to the mastery of a single magical Immuto.',
			text:'Choose an Immuto which the character has access to in at least one Grimoire. Whenever the character casts a Spell from any Grimoire, he may use the chosen Immuto.',
			trigger:'',
			limit:'',
			fill:2,
		},
	},
	guard : {
		book:'Fated Almanac',
		'Now you are pissing me off' : {
				name:'Теперь ты меня бесишь',
				requirement:'',
				story:'',
				text:'После провала дуэли Close Combat duel во время dramatic time, можно вытянуть карту на руку. Эпилог: можно развить любой Close Combat skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Stoic Defender' : {
				name:'Стойкий защитник',
				requirement:'',
				story:'The character has learned to grimly shield himself from attacks.',
				text:'This character gains the following Trigger on all Defense Duels:',
				trigger:'♦ Just a Glance: When suffering damage, reduce the amount of damage suffered by 1, to a minimum of 1. ',
				limit:'',
			},
		'Inevitable Defence' : {
				name:'Неизбежная защита',
				requirement:'',
				story:'This character doesn’t rely on luck or the whims of fate when he adopts a defensive posture.',
				text:'When this character takes a Defensive Stance Action, he does not have to discard a Twist Card. In addition, when this character takes a Defensive Stance Action, all friendly characters also gain + to Defense Challenges while they remain within 2 yards of him.',
				trigger:'',
				limit:'',
			},
		'Take The Hit' : {
				name:'Принять удар',
				requirement:'',
				story:'Leaping in front of a friend, the character takes a hit for him.',
				text:'The character may discard a card from his Control Hand after an attack hits a target character (friendly or not) within 2 yards, but before damage is dealt. This character moves to a position in front of the target character. This character takes the hit for the target character and Damage Flip suffers - .',
				trigger:'',
				limit:'',
			},
		'Hard To Wound' : {
				name:'Тяжело ранить',
				requirement:'',
				story:'This rugged character can resist damage better than most.',
				text:'This character imposes a - to any Damage Flip made against him.',
				trigger:'',
				limit:'A character may have this Talent up to two times, and the effects stack.',
				fill:2,
			},
		'Flurry' : {
				name:'Шквал',
				requirement:'',
				story:'Когда дело доходит до нанесения стремительных атак с оружием в руках, этот персонаж делает это эффективно, и скорее всего жестоко.',
				text:'Выберите навык Ближнего Боя (Close Combat). Этот персонаж имеет доступ к следующему атакующему Действию с выбранным навыком: (2) Шквал: Вы можете сбросить карту чтобы выполнить три (1) ОД (AP) удара оружием Ближнего Боя, использующим выбранный навык, против одной цели.',
				trigger:'',
				limit:'Вы можете взять этот Талант несколько раз, каждый раз он должен выбирать разный навык Ближнего Боя.',
				fill:2,
			},
		'Unyielding' : {
				name:'Неуступчивый',
				requirement:'',
				story:'The character is a master of defensive skills, protecting both himself and his companions with ease.',
				text:'The character reduces the cost of Defensive Stance Actions by 1 AP (to a minimum of 0).',
				trigger:'',
				limit:'',
			},
	},
	gunfighter : {
		book:'Fated Almanac',
		'Finger on the trigger' : {
				name:'Палец на курке',
				requirement:'',
				story:'',
				text:'После провала дуэли Ranged Combat duel during dramatic time, можно вытянуть карту на руку. Эпилог: можно развить любой Ranged Combat skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Quick Draw' : {
				name:'Быстрое выхватывание',
				requirement:'',
				story:'С ослепительной скоростью вы можете достать свое оружие, иногда быстрее чем кто-либо заметит.',
				text:'Вы получаете следующий триггер на любой Переворот (Challenge Flip) (включая определение Инициативы). Также, вы считаете действие (1) "Приготовить оружие" как (0) "Приготовить оружие".',
				trigger:'♥ Быстрое выхватывание: Выполнить действие "Приготовить оружие" незамедлительно после определения результата проверки.',
				limit:'',
			},
		'Call Out' : {
				name:'Вызов',
				requirement:'',
				story:'Some men just have a knack for jawin’ in such a way as to call attention to themselves, even in a fight.',
				text:'This character may discard a card from his Control Hand to give a target character a -3 penalty on any attack Action that does not target this character.',
				trigger:'',
				limit:'',
			},
		'Gunfighter' : {
				name:'Стрелок',
				requirement:'',
				story:'This character is comfortable with a ranged weapon, even up close.',
				text:'Choose a Ranged skill; this character may choose to use the weapon as if its Range were melee-2 yards. A character may have this Talent multiple times, choosing a different Ranged skill each time.',
				trigger:'',
				limit:'',
				fill:2,
			},
		'No Time For This' : {
				name:'Нет времени на это',
				requirement:'',
				story:'It’s been said that if brute force doesn’t work, enough wasn’t employed, and this character understands the unsubtle truth of that statement.',
				text:'Whenever this character is involved in an Продолжительного испытания (Ongoing Challenge) he may choose to make one of the Challenge Flips (at any point in the Action) using his Pistols or Shotgun skill instead of the appropriate skill (he still uses the appropriate Aspect, however).',
				trigger:'',
				limit:'',
			},
		'Rapid Fire' : {
				name:'Скорострельный',
				requirement:'',
				story:'Whether it is fanning a revolver, or quickly levering a rifle, this character is capable of burning through ammunition.',
				text:'Choose a Ranged Combat skill. This character has access to the following attack Action with the chosen skill:',
				trigger:'(2) Скорострельный: Вы можете сбросить карту чтобы выполнить три (1) ОД атаки дальнобойным оружием использующим выбранный навык против одной цели.',
				limit:'A character may have this Talent multiple times, each time he must choose a different Ranged Combat skill.',
				fill:2,
			},
		'Ranged Expert' : {
				name:'Эксперт дальнего боя',
				requirement:'',
				story:'Making Ranged attacks is second nature to this character, who is able to point and shoot with terrifying efficiency.',
				text:'This character generates an additional AP on its turn, which must be used to make a strike with a Ranged weapon.',
				trigger:'',
				limit:'',
			},
	},
	mercenary : {
		book:'Fated Almanac',
		'Deadset' : {
				name:'Захват цели',
				requirement:'',
				story:'',
				text:'После провала дуэли Ranged Combat duel during dramatic time, можно вытянуть карту на руку. Эпилог: можно развить любой Ranged Combat skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Speed Loading' : {
				name:'Скоростная перезарядка',
				requirement:'',
				story:'The most professional of combatants understand that running out of bullets can be a death sentence, and this character has taken steps to ensure that this rarely happens to him.',
				text:'Choose a type of firearm skill (Long Arms, Pistols, Shotguns, or Heavy Weapons). The character gains the following Trigger on any attack Action with that type of weapon.',
				trigger:'♥: Reload this weapon if its Reload AP cost is 2 or lower.',
				limit:'',
			},
		'Gruesome Attack' : {
				name:'Ужасная атака',
				requirement:'',
				story:'Combat is a dangerous thing, and a skilled warrior knows exactly where to put the bullet or blade.',
				text:'Choose a single Melee or Ranged skill. All Critical Effect Flips generated by attacks using the chosen skill gain +. A character may have this ability multiple times (even with the same skill) and the effects stack.',
				trigger:'',
				limit:'',
				fill:2,
			},
		'Tricky Shot' : {
				name:'Сложный выстрел',
				requirement:'',
				story:'The character is highly adept at pulling off tricky shots in a variety of conditions.',
				text:'Choose a Ranged Combat skill. While making a Ranged attack Challenge Flip with the chosen skill, the character may choose to ignore one negative Fate Modifier source.',
				trigger:'',
				limit:'',
			},
		'Coin For Kills' : {
				name:'Монета за убийство',
				requirement:'',
				story:'It doesn’t matter if he is hunting a posted bounty or was paid to fight, this character is highly motivated by profit to commit violence.',
				text:'The character gains + to the Damage Flip of any attack against a target he was paid to fight (or kill). It falls to Fatemaster’s discretion what counts as “paid to fight,” but for the most part, if the character was hired to commit violence, he should have access to this ability in pursuit of that contract.',
				trigger:'',
				limit:'',
			},
		'Relentless' : {
				name:'Неумолимый',
				requirement:'',
				story:'Вы неверите, что жизнь страшна, даже ваша.',
				text:'У вас иммунитет к эффектам Ужаса (Horror).',
				trigger:'',
				limit:'',
			},
		'Endless Pursuit' : {
				name:'Бесконечное преследование',
				requirement:'',
				story:'When this character is hired to track a target, he never gives up.',
				text:'This character gains + to any Defense Flips against attacks made by targets he was paid to fight. Furthermore, the character may choose to declare anyone with a bounty on their head as someone he was paid to fight (or kill).',
				trigger:'',
				limit:'',
			},
	},
	overseer : {
		book:'Fated Almanac',
		'Oversight' : {
				name:'Надзор',
				requirement:'',
				story:'',
				text:'При провале Social duel, можно вытянуть карту на руку. Эпилог: можно развить любой Social skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Concerted Effort' : {
				name:'Согласованные усилия',
				requirement:'',
				story:'A group is always better acting simultaneously, at least in this character’s eyes.',
				text:'When friendly characters make Initiative Flips, they may choose to not make an Initiative Flip and use this character’s Initiative value instead.',
				trigger:'',
				limit:'',
			},
		'Time Is Money' : {
				name:'Время деньги',
				requirement:'',
				story:'When a job needs doing, it needs doing quick.',
				text:'Choose a skill, this character generates an additional Margin of Success whenever he succeeds on a Challenge Flip during an Продолжительного испытания (Ongoing Challenge) with the chosen skill.',
				trigger:'',
				limit:'',
			},
		'Work Smarter' : {
				name:'Работать умнее',
				requirement:'',
				story:'With stern looks or shouted abuse, this character can make anyone focus a little bit more intensely.',
				text:'This character may discard a card from his Control Hand to add the Suit of the discarded card to the Initial Acting value of himself or another friendly character that can see or hear him.',
				trigger:'',
				limit:'',
			},
		'Delegate' : {
				name:'Делегировать',
				requirement:'',
				story:'This character is adept at making sure others have the opportunity to protect him.',
				text:'The character gains the following Trigger to all Defense Duels:',
				trigger:'♣ “Делегировать”: When damage is dealt to this character, a friendly character within 3 yards becomes the target of the attack instead.',
				limit:'',
			},
		'You Lazy So & So' : {
				name:'Ты ленивый ...',
				requirement:'',
				story:'A tolerance for the faults (or suffering) of others doesn’t impede this character in the slightest.',
				text:'This character may discard a card from his Control Hand to allow a friendly character that can see or hear him to ignore the effects of all Critical Effects until the end of that character’s turn. The character must still make any challenges (such as Unconsciousness challenges) he is called upon to make by his injuries, he simply ignores the effects until the end of his turn.',
				trigger:'',
				limit:'A character may have this ability multiple times, each time after the first, the duration of the effect lasts an additional turn.',
				fill:2,
			},
		'Now Men!' : {
				name:'Сейчас парни!',
				requirement:'',
				story:'A life of leading men has given the character a commanding presence in an emergency.',
				text:'This character may discard three cards from his Control Hand. If he does, every friendly character that can see or hear him may immediately take a 1 AP Action in any order that this character wishes.',
				trigger:'',
				limit:'',
			},
	},
	performer : {
		book:'Fated Almanac',
		'Flare for the dramatic' : {
				name:'Вспышка драматизма',
				requirement:'',
				story:'',
				text:'При провале Social duel, можно вытянуть карту на руку. Эпилог: можно развить любой Social skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Powerful Impression' : {
				name:'Сильное впечатление',
				requirement:'',
				story:'This character draws attention whenever he wants, and is used to the spotlight.',
				text:'This character gains the following Trigger on all Social Duels:',
				trigger:'♦ Impress: : After resolving, draw a card.',
				limit:'',
			},
		'Grace Under Fire' : {
				name:'Изящество под огнем',
				requirement:'',
				story:'As they say, the show must go on, and this character handles danger, as well as the unexpected, with grace.',
				text:'This character may use Grace instead of Speed to derive his Defense Aspect, as well he may use Grace instead of Speed during Initiative Flips.',
				trigger:'',
				limit:'',
			},
		'Helluva Entrance' : {
				name:'Эффектный вход',
				requirement:'',
				story:'This character never fails to make an impression when he enters the room.',
				text:'This character gains + to the first Challenge Flip he makes in any scene.',
				trigger:'',
				limit:'',
			},
		'Classically Trained' : {
				name:'Классическое образование',
				requirement:'',
				story:'This character has received training from a true thespian, or at least pretends to have.',
				text:'Choose a single Social skill, the maximum rating for this skill is 6 (instead of 5).',
				trigger:'',
				limit:'A character may have the Classically Trained Talent multiple times, but each time a different skill must be chosen.',
				fill:2,
			},
		'Graceful Exit' : {
				name:'Изящный выход',
				requirement:'',
				story:'The character is adept at removing themselves from view, or becoming unassuming.',
				text:'This character may discard a card from his Control Hand to impose a -- on any attack that targets him directly (not Area attacks), until the end of his next Turn.',
				trigger:'',
				limit:'',
			},
		'That\'s Showbiz' : {
				name:'Это шоубизнес',
				requirement:'',
				story:'In any social situation, this character is adept at becoming liked, even when he wishes to coerce a mark.',
				text:'The character may exchange Charm for any other Aspect when he makes a Social Challenge.',
				trigger:'',
				limit:'',
			},
	},
	pioneer : {
		book:'Fated Almanac',
		'Rugged individual' : {
				name:'Прочная личность',
				requirement:'',
				story:'',
				text:'При провале Training duel, можно вытянуть карту на руку. Эпилог: можно развить любой Training skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Born Under A Wandering Star' : {
				name:'Рожденный под странствующей звездой',
				requirement:'',
				story:'While navigating Malifaux is extremely difficult (as traditional navigation uses the laws of Earth), this character is capable of navigating any environment.',
				text:'The character never suffers negative Fate Modifiers to his Navigation or Wilderness tests.',
				trigger:'',
				limit:'',
			},
		'Circle The Wagons' : {
				name:'Повозки в круг',
				requirement:'',
				story:'This character knows how to quickly fortify an area for defense.',
				text:'The character can discard a card from his Control Hand to make all friendly characters that can hear him treat all cover as Hard cover.',
				trigger:'',
				limit:'',
			},
		'Tough as Nails' : {
				name:'Жесткий как гвоздь',
				requirement:'',
				story:'This rugged character just doesn’t concern himself with pain or suffering, allowing him to ignore part of almost any attack.',
				text:'When attacking this character with a Ranged or Melee strike, the Attacker cannot declare any Triggers.',
				trigger:'',
				limit:'',
			},
		'Ornery' : {
				name:'Плохиш',
				requirement:'',
				story:'There are some men who just have to be dragged kicking and screaming into the cold darkness of death.',
				text:'When the character suffers a Critical Effect the effect suffers a -3 penalty to the Flip. A character may have this Talent more than once, and the effects stack.',
				trigger:'',
				limit:'',
				fill:2,
			},
		'Soldier On' : {
				name:'Начеку',
				requirement:'',
				story:'There are some men who won’t quit, and they can inspire others to press on despite the worst the world can throw at them.',
				text:'At the beginning of Dramatic Time this character may heal 2/3/5 damage, if he has 1 or more Wound remaining. In addition, he may choose to have any friendly character that can hear him also heal 2/3/5 damage, if the character has 1 or more Wounds remaining.',
				trigger:'',
				limit:'',
			},
		'Relentless' : {
				name:'Неумолимый',
				requirement:'',
				story:'',
				text:'The character doesn\'t believe that life is scared, not even his own. This character is immune to the effects of Horror.',
				trigger:'',
				limit:'',
			},
	},
	scrapper : {
		book:'Fated Almanac',
		'Bloody Minded' : {
				name:'Кровожадный',
				requirement:'',
				story:'',
				text:'После провала дуэли Ближнего Боя (Close Combat) во время dramatic time, можно вытянуть карту на руку. Эпилог: можно развить любой навык Ближнего Боя (Close Combat) в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Close the Gap' : {
				name:'Сомкнуть разрыв',
				requirement:'',
				story:'Вы не боитесь ворваться в битву и знаете как использовать это в свою пользу.',
				text:'Когда вы заявляете Действие Нападения (Charge Action) вы можете вытянуть карту на руку.',
				trigger:'',
				limit:'',
			},
		'Flurry' : {
				name:'Шквал',
				requirement:'',
				story:'Когда дело доходит до нанесения стремительных атак с оружием в руках, вы делаете это эффективно, и скорее всего жестоко.',
				text:'Выберите навык Ближнего Боя (Close Combat). Вы имеете доступ к следующему атакующему Действию с выбранным навыком:',
				trigger:'(2) Шквал: можете сбросить карту с руки чтобы выполнить три (1) ОД (AP) удара оружием Ближнего Боя, использующим выбранный навык, против одной цели.',
				limit:'Вы можете взять этот Талант несколько раз, каждый раз он должен выбирать разный навык Ближнего Боя.',
				fill:2,
			},
		'Recovery' : {
				name:'Восстановление',
				requirement:'',
				story:'Царапины и порезы значат для вас мало, и вы можете быстро оправиться после травмы.',
				text:'Вы получаете "+" ко всем Переворотам Лечения (Healing Flip) которые  делаете.',
				trigger:'',
				limit:'Вы можете взять этот Талант больше одного раза, и эффекты складываются.',
			},
		'Watch Them All' : {
				name:'Следить за всеми ними',
				requirement:'',
				story:'Способность отслеживать противника в бою переносится и на социальные ситуации.',
				text:'Вы получаете "+" ко всем попыткам противостоять угрозам (intimidation) или обману (deception). Также вы получаете "+" ко всем Переворотам Инициативы (Initiative Flips).',
				trigger:'',
				limit:'',
			},
		'Wicked' : {
				name:'Злобный',
				requirement:'',
				story:'Каждая брешь это возможность ударить оппонента и вы не медлите этим воспользоваться.',
				text:'Когда вы совершаете удерживающий удар (disengaging strike), вы наносите урон своим оружием, помимо предотвращения движения цели.',
				trigger:'',
				limit:'',
			},
		'Melee Expert' : {
				name:'Эксперт Ближнего боя',
				requirement:'',
				story:'Когда вы решаете ранить противника, то невероятно искусны в этом деле. ',
				text:'Вы получаете дополнительное ОД (AP) на свой ход, которое может быть использовано только для атаки оружием ближнего боя (Melee).',
				trigger:'',
				limit:'',
			},
	},
	tinkerer : {
		book:'Fated Almanac',
		'Gear head' : {
				name:'Шестеренки в голове',
				requirement:'',
				story:'',
				text:'После провала Магической дуэли во время dramatic time, можно вытянуть карту на руку. Эпилог: можно развить любой Магический (Magic) навык в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Push the Limits' : {
				name:'Расширить границы',
				requirement:'',
				story:'Вы можете требовать от машины большего, расширяя пределыы ее возможностей.',
				text:'Вы можете заставить конструкта под вашим контролем получить 1 урон, который не может быть понижен. Если вы это делаете, конструкт получает "+" на свое следующее действие. Вы можете использовать эту способность на себе если имеете минимум одну пневматическую конечность и эта конечность используется в действии.',
				trigger:'',
				limit:'',
			},
		'Combat Construct' : {
				name:'Боевой Конструкт',
				requirement:'',
				story:'Все ваши конструкты способны вести бой.',
				text:'Когда вы используете Создание артефактов (Artefacting) для создания или ремонта конструкта, вы может дать ему навык пневматики (pneumatic) равный своему навыку Создания артефактов (Artefacting).',
				trigger:'',
				limit:'',
			},
		'Percussive Maintenance' : {
				name:'Ударный ремонт',
				requirement:'',
				story:'Точным ударом в нужное место машины, вы переопределяете отказавшие компоненты, позволяя функционировать дальше.',
				text:'Все проверки (Artefacting) при ремонте штуковин (contraptions) или конструктов (constructs) получают следующий триггер:',
				trigger:'♣ Преимущество: Получите 1 дополнительный Признак успеха (Margin of Success).',
				limit:'',
			},
		'Unrealistic Expectation' : {
				name:'Нереальные ожидания',
				requirement:'',
				story:'Постоянная работа в мастерской позволяет вам улучшить производительность ваших пневматических конечностей.',
				text:'Ваши пневматические конечности улучшают один физический аспект (Physical Aspect) на 1 (как группа), и вы можете изменить какой аспект улучшен одним часом работы (tinkering). Также, сложность (TN) починки конечностей производимой вами снижается на 5, до минимума в 1.',
				trigger:'',
				limit:'',
			},
		'Multi-Tasker' : {
				name:'Многозадачный',
				requirement:'',
				story:'Вы можете командовать несколькими конструктами словом или жестом.',
				text:'Когда вы выполняете (1) "Приказ" (Order Action), вы можете отдавать приказы двум подчиненным конструктам вместо одного, и приказы могут быть разными.',
				trigger:'',
				limit:'Вы можете взять этот Талант несколько раз, и эффект накапливается (увеличивая число доступных для приказа конструктов на 1 каждый раз).',
				fill:2,
			},
		'Over Pressure' : {
				name:'Под давлением',
				requirement:'',
				story:'Вы способны быстро оснастить свое пневматическое снаряжение и улучшения для скоростного действия.',
				text:'Вы получаете следующий триггер на все пневматические атаки:',
				trigger:'♣: В конце этого хода вы можете выполнить одну дополнительную атаку пневматическим оружием. Дополнительная атака не может заявлять триггеры. Этот триггер может быть активирован только раз в ход.',
				limit:'',
			},
	},
	wastrel : {
		book:'Fated Almanac',
		'Educated' : {
				name:'Образованный',
				requirement:'',
				story:'',
				text:'При провале Expertise duel, можно вытянуть карту на руку. Эпилог: можно развить любой Expertise skill в дополнение к вариантам развития навыков.',
				trigger:'',
				limit:'',
			},
		'Luck of the Draw' : {
				name:'Удачная лотерея',
				requirement:'',
				story:'Некоторые просто рождены удачливыми.',
				text:'Вы тянете 2 карты когда Мастер тасует колоду, вместо 1.',
				trigger:'',
				limit:'',
			},
		'Cards Up A Sleeve' : {
				name:'Карты в рукаве',
				requirement:'',
				story:'While many card players know how to cheat a card into their own hands, it takes a special Talent to load someone else’s.',
				text:'The character may place one card from his Control Hand face up on the table in front of him. Any player may discard a card from their Control Hand to Cheat Fate with the face up card. Afterwards, the face up card is discarded into the appropriate discard pile.',
				trigger:'',
				limit:'',
			},
		'Trump Card' : {
				name:'Козырь',
				requirement:'',
				story:'Вы всегда знаете то, чего не знают другие.',
				text:'Во время Dramatic Time, this character can discard a card from his Control Hand after he has taken his turn. If he does so, he may look at the top 3 cards of the Fate Deck and replace them in any order. He may not tell anyone what cards are there, but he may hint that they are good or bad.',
				trigger:'',
				limit:'',
			},
		'All In' : {
				name:'Ва банк',
				requirement:'',
				story:'Иногда нужно рискнуть всем и надеяться, что удача на твоей стороне.',
				text:'Вы получаете "+" ко все дуэлям пока у вас нет карт на руке.',
				trigger:'',
				limit:'',
			},
		'Play For Blood' : {
				name:'Игра до крови',
				requirement:'',
				story:'When pressed into a corner, this character knows the risks and becomes even more dangerous.',
				text:'When this character is suffering from one or more Critical Effects, all of his Challenges gain the following Trigger: A character may have this Talent multiple times, increasing the Margins of Success gained by 1 each additional time.',
				trigger:'♠ "Преимущество": Gain 1 additional Margin of Success.',
				limit:'',
				fill:2,
			},
		'Fifty-Fifty Chance' : {
				name:'Шансы пятьдесят на пятьдесят',
				requirement:'',
				story:'Каждый игрок знает, что иногда, нужно просто подбросить монету и довериться судьбе.',
				text:'Once per Dramatic Time, this character may “stack the deck.” To stack the deck, the player goes through the discard pile and Fate Deck to find both Jokers. The Fatemaster then randomly shuffles one into the deck (along with the discard pile) and then places the other on top of the deck. Nobody looks at which is actually on top.',
				trigger:'',
				limit:'',
			},
	},
	deathmarshal : {
		book:'Advanced (Fated Almanac)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	animator : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	augmented : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	collaborator : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	engineer : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	illusionist : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	infiltrator : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	mage : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	primal : {
		book:'Into the Steam',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	shapeshifter : {
		book:'Advanced (Into the Steam)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	decemberacolyte : {
		book:'Advanced (Into the Steam)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	silentone : {
		book:'Advanced (Into the Steam)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	demolitionist : {
		book:'Advanced (Into the Steam)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	bully : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	chemist : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	forgotten : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	ghosteater : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	ghoul : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	medium : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	necromancer : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
	sawbones : {
		book:'Under Quarantine',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
		abettorofobliteration : {
		book:'Advanced (Under Quarantine)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
		exorcist : {
		book:'Advanced (Under Quarantine)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
		revenant : {
		book:'Advanced (Under Quarantine)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
		revivalist : {
		book:'Advanced (Under Quarantine)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
		studentoftransmortis : {
		book:'Advanced (Under Quarantine)',
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
		'' : {
				name:'',
				requirement:'',
				story:'',
				text:'',
				trigger:'',
				limit:'',
			},
	},
}


function TalentsTable(){
	var arr = [];

	for (var p in talents) {
		arr.push(p);
	}
	// console.log(arr)
	// console.log(arr.length)
	for(var t = 0; t < arr.length; t++){
		// console.log(arr[t])
		// console.log(talents[arr[t]])

		var table = $('<table />')
		table.attr('cellpadding',"0px")
		table.attr('cellspacing','0px')
		table.attr('width','100%')
		table.attr('class','talentstable')
		table.attr('id','talents-'+arr[t])
		table.css('display','none')
		var pursuit = arr[t]
		var name = pursuit
		if(pursuit == 'general'){name = 'Общие таланты'}
		if(pursuit == 'academic'){name = 'Академик'}
		if(pursuit == 'criminal'){name = 'Преступник'}
		if(pursuit == 'dabbler'){name = 'Дилетант'}
		if(pursuit == 'drudge'){name = 'Трудяга'}
		if(pursuit == 'graverobber'){name = 'Гробокопатель'}
		if(pursuit == 'guard'){name = 'Гвардеец'}
		if(pursuit == 'gunfighter'){name = 'Стрелок'}
		if(pursuit == 'mercenary'){name = 'Наемник'}
		if(pursuit == 'overseer'){name = 'Смотритель'}
		if(pursuit == 'performer'){name = 'Исполнитель'}
		if(pursuit == 'pioneer'){name = 'Первопроходец'}
		if(pursuit == 'scrapper'){name = 'Задира'}
		if(pursuit == 'tinkerer'){name = 'Жестянщик'}
		if(pursuit == 'wastrel'){name = 'Кутила'}
		if(pursuit == 'deathmarshal'){name = 'Маршал Смерти'}
		if(pursuit == 'animator'){name = 'Аниматор'}
		if(pursuit == 'augmented'){name = 'Дополненный'}
		if(pursuit == 'collaborator'){name = 'Пособник'}
		if(pursuit == 'engineer'){name = 'Инженер'}
		if(pursuit == 'illusionist'){name = 'Иллюзионист'}
		if(pursuit == 'infiltrator'){name = 'Лазутчик'}
		if(pursuit == 'mage'){name = 'Маг'}
		if(pursuit == 'primal'){name = 'Первобытный'}
		if(pursuit == 'shapeshifter'){name = 'Перевертыш'}
		if(pursuit == 'decemberacolyte'){name = 'Аколит Декабря'}
		if(pursuit == 'silentone'){name = 'Безмолвный'}
		if(pursuit == 'demolitionist'){name = 'Подрывник'}
		if(pursuit == 'bully'){name = 'Хулиган'}
		if(pursuit == 'chemist'){name = 'Химик'}
		if(pursuit == 'forgotten'){name = 'Забытый'}
		if(pursuit == 'ghosteater'){name = 'Пожиратель духов'}
		if(pursuit == 'ghoul'){name = 'Упырь'}
		if(pursuit == 'medium'){name = 'Медиум'}
		if(pursuit == 'necromancer'){name = 'Некромант'}
		if(pursuit == 'sawbones'){name = 'Костоправ'}
		if(pursuit == 'abettorofobliteration'){name = 'Пособник Забвения'}
		if(pursuit == 'exorcist'){name = 'Экзорцист'}
		if(pursuit == 'revenant'){name = 'Призрак'}
		if(pursuit == 'revivalist'){name = 'Реаниматор'}
		if(pursuit == 'studentoftransmortis'){name = 'Студент Трансмортиса'}
		var tr = $('<tr />');
		var td0 = $('<td />',{class:'talentstable-pursuit',text:name});
		td0.attr('colspan',"2");
		if (pursuit != 'general'){
			td0.append($('<input />',{type:'button',class:'btn talents-btn',value:'скрыть','click':function(){
				hideElem(this)
			}}))
		}
		
		table.append(tr.append(td0))

		var tr = $('<tr />')
		var td = $('<td />')
		var div0 = $('<div />',{id:pursuit+'-talentstable-wrap',class:'talentstable-wrap'});
		var div1 = $('<div />',{id:pursuit+'-talentstable-img',class:'talentstable-img'});
		var div2 = $('<div />',{id:pursuit+'-talentstable-options',class:'talentstable-options'});
		var div3 = $('<div />',{id:pursuit+'-talentstable-summary',class:'talentstable-summary'});
		var div4 = $('<div />',{id:pursuit+'-talentstable-gear',class:'talentstable-gear'});
		
		td.attr('colspan',"3");
		table.append(tr.append(td.append(div1).append(div0.append(div2).append(div3)).append(div4)))

		var arr1 = [];

		for (var p in talents[arr[t]]) {
			// console.log(talents[arr[t]])
			arr1.push(p);
		}
		// console.log(arr1)
		// console.log('ARR1: '+arr1)
		// console.log(arr1.length)
		for(var i = 0; i < arr1.length; i++){
			// console.log(arr1[i])
			if(arr1[i] == 'book'){
				var book = talents[arr[t]].book
				// console.log(book)
				td0.prepend(book+': ')
			}
			else{
				var tr = $('<tr />');
				var td1 = $('<td />',{class:'talentstable-name'});
				var td2 = $('<td />',{class:'talentstable-text'});
				// td1.append(arr1[i])

				var name = talents[arr[t]][arr1[i]].name
				if(name){
					// console.log('name: '+name)
					td1.append(name+'<br>('+arr1[i]+')')
				}
				else{
					td1.append(arr1[i])
				}
				// console.log(talents[arr[t]][arr1[i]])
				story = talents[arr[t]][arr1[i]].story
				if(story){
					// console.log('Story: '+story)
					td2.append('<p class="talents-story">'+story+'</p>')
				}
				var requirement = talents[arr[t]][arr1[i]].requirement
				if(requirement){
					td2.append('<p class="talents-requirement">Требование: '+requirement+'</p>')
				}
				var text = talents[arr[t]][arr1[i]].text
				if(text){
					td2.append('<p class="talents-text">'+text+'</p>')
				}
				var trigger = talents[arr[t]][arr1[i]].trigger
				if(trigger){
					td2.append('<p class="talents-trigger">'+trigger+'</p>')
				}
				var limit = talents[arr[t]][arr1[i]].limit
				if(limit){
					td2.append('<p class="talents-limit">'+limit+'</p>')
				}
				var fill = talents[arr[t]][arr1[i]].fill
				if(fill){
					console.log('fill: '+fill)
					console.log('numeric: '+$.isNumeric(fill))
					if($.isNumeric(fill) == true){
						var div1 = $('<div />',{class:'talents-fill'});
						var div2 = $('<div />',{class:'talents-fill'});
						var div3 = $('<div />',{class:'talents-fill'});
						if(fill == 1){
							td2.append(div1)
							// $('.talents-fill').css('width','400px')
							// td2.append('<div class="talents-fill" id="'+arr1[i]+'-fill">'+'[___]'+'</div>')
						}
						if(fill == 2){
							td2.append(div1).append(div2)
							// $('.talents-fill').css('width','200px')
							// td2.append('<div class="talents-fill" id="'+arr1[i]+'-fill">'+'[___][___]'+'</div>')
						}
						if(fill == 3){
							td2.append(div1).append(div2).append(div3)
							// $('.talents-fill').css('width','50px')
							// td2.append('<div class="talents-fill" id="'+arr1[i]+'-fill">'+'[___][___][___]'+'</div>')
						}
					}
					else{
						td2.append('<div class="talents-fill">'+fill+'</div>')
					}
				}
				table.append(tr.append(td1).append(td2))
				console.log($('.talentstable-text').css('width'))
			}
		}
		$('#popup').append(table)
	}
}

TalentsTable()

function getTalent(card,type){
	var arr2 = [];
	var cardtalent = talents[card]
	for (var p in cardtalent) {
			arr2.push(p);
		}
		if(type == 'n'){
			
			if(cardtalent[arr2[1]].name){
				return cardtalent[arr2[1]].name
			}
			else{
				return arr2[1]
			}
			
		}
			else if(type == 't'){
				return cardtalent[arr2[1]].text
			}
				else{
					'none'
				}
}

function showElem(elem,type){
// console.log(type)
arr = elem.split('-')
// console.log(arr)
// console.log(arr[0])
	if(type == 't'){
			$('.talentstable').hide()
			$('#popup').hide()
			$('#talents-'+arr[0]).show()
			$('#popup').show()
			$('#page').hide()
	}
	if(type == 'c'){
			$('.talentstable').hide()
			$('#popup').hide()
			$('#page').hide()
			$('#talents-'+arr[0]).show()
			$('#'+arr[0]+'-front').show()
			$('#popup').show()
			
	}
}

function hideElem(elem){
	$(elem).parents('table').hide()
	$('#popup').hide()
	$('#page').show()
}

// $('#popup').toggle()
// $('.talentstable').hide()
// $('#page').toggle()